package com.springmvc.videoteca.spring.model;
// Generated 19/07/2015 12:42:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pelicula generated by hbm2java
 */
@Entity
@Table(name="pelicula"
    ,schema="public"
)
public class Pelicula  implements java.io.Serializable {


     private int id;
     private String directores;
     private String sinapsis;
     private String nombre;
     private String duracion;
     private String restriccion;
     private String nacionalidad;
     private Date fechaestreno;
     private String imagen;
     private String trailerlink;
     private Set peliculasalas = new HashSet(0);

    public Pelicula() {
    }

	
    public Pelicula(int id, String directores, String sinapsis, String nombre, String duracion, String restriccion, String nacionalidad, Date fechaestreno, String imagen, String trailerlink) {
        this.id = id;
        this.directores = directores;
        this.sinapsis = sinapsis;
        this.nombre = nombre;
        this.duracion = duracion;
        this.restriccion = restriccion;
        this.nacionalidad = nacionalidad;
        this.fechaestreno = fechaestreno;
        this.imagen = imagen;
        this.trailerlink = trailerlink;
    }
    public Pelicula(int id, String directores, String sinapsis, String nombre, String duracion, String restriccion, String nacionalidad, Date fechaestreno, String imagen, String trailerlink, Set peliculasalas) {
       this.id = id;
       this.directores = directores;
       this.sinapsis = sinapsis;
       this.nombre = nombre;
       this.duracion = duracion;
       this.restriccion = restriccion;
       this.nacionalidad = nacionalidad;
       this.fechaestreno = fechaestreno;
       this.imagen = imagen;
       this.trailerlink = trailerlink;
       this.peliculasalas = peliculasalas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="directores", nullable=false, length=200)
    public String getDirectores() {
        return this.directores;
    }
    
    public void setDirectores(String directores) {
        this.directores = directores;
    }

    
    @Column(name="sinapsis", nullable=false, length=200)
    public String getSinapsis() {
        return this.sinapsis;
    }
    
    public void setSinapsis(String sinapsis) {
        this.sinapsis = sinapsis;
    }

    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="duracion", nullable=false, length=20)
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }

    
    @Column(name="restriccion", nullable=false, length=20)
    public String getRestriccion() {
        return this.restriccion;
    }
    
    public void setRestriccion(String restriccion) {
        this.restriccion = restriccion;
    }

    
    @Column(name="nacionalidad", nullable=false, length=50)
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaestreno", nullable=false, length=13)
    public Date getFechaestreno() {
        return this.fechaestreno;
    }
    
    public void setFechaestreno(Date fechaestreno) {
        this.fechaestreno = fechaestreno;
    }

    
    @Column(name="imagen", nullable=false, length=100)
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    
    @Column(name="trailerlink", nullable=false, length=200)
    public String getTrailerlink() {
        return this.trailerlink;
    }
    
    public void setTrailerlink(String trailerlink) {
        this.trailerlink = trailerlink;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pelicula")
    public Set getPeliculasalas() {
        return this.peliculasalas;
    }
    
    public void setPeliculasalas(Set peliculasalas) {
        this.peliculasalas = peliculasalas;
    }




}


