package com.springmvc.videoteca.spring.model;
// Generated 19/07/2015 03:21:56 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reserva generated by hbm2java
 */
@Entity
@Table(name = "reserva", schema = "public"
)
public class Reserva implements java.io.Serializable {

    private int id;
    private Cliente cliente;
    private Peliculasala peliculasala;
    private int cantidad;

    public Reserva() {
    }

    public Reserva(int id, Cliente cliente, Peliculasala peliculasala, int cantidad) {
        this.id = id;
        this.cliente = cliente;
        this.peliculasala = peliculasala;
        this.cantidad = cantidad;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "clienteid", nullable = false)
    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "peliculasalaid", nullable = false)
    public Peliculasala getPeliculasala() {
        return this.peliculasala;
    }

    public void setPeliculasala(Peliculasala peliculasala) {
        this.peliculasala = peliculasala;
    }

    @Column(name = "cantidad", nullable = false)
    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

}
