package com.springmvc.videoteca.spring.model;
// Generated 19/07/2015 12:42:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sala generated by hbm2java
 */
@Entity
@Table(name="sala"
    ,schema="public"
)
public class Sala  implements java.io.Serializable {


     private int id;
     private int numero;
     private String tipo;
     private int capacidad;
     private Set peliculasalas = new HashSet(0);

    public Sala() {
    }

	
    public Sala(int id, int numero, String tipo, int capacidad) {
        this.id = id;
        this.numero = numero;
        this.tipo = tipo;
        this.capacidad = capacidad;
    }
    public Sala(int id, int numero, String tipo, int capacidad, Set peliculasalas) {
       this.id = id;
       this.numero = numero;
       this.tipo = tipo;
       this.capacidad = capacidad;
       this.peliculasalas = peliculasalas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="numero", nullable=false)
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }

    
    @Column(name="tipo", nullable=false, length=50)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="capacidad", nullable=false)
    public int getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sala")
    public Set getPeliculasalas() {
        return this.peliculasalas;
    }
    
    public void setPeliculasalas(Set peliculasalas) {
        this.peliculasalas = peliculasalas;
    }




}


